### ISSUE TITLE
tui.ctrl.checkbox("id").value()的疑问

### ISSUE THREAD

**Issue by xhy008** [ThorQin/tui#2]
tui.ctrl.checkbox.ts中的如下代码：

```
value(): any;
value(val?: any): Checkbox;
value(val?: any): any {
    if (typeof val !== tui.undef) {
        this.attr("data-value", JSON.stringify(val));
        return this;
    } else {
        val = this.attr("data-value");
        if (val === null) {
            return null;
        } else {
            try {
                return eval("(" + val + ")");
            } catch (err) {
                return null;
            }
        }
    }
}
```

为什么不直接返回val变量，而是要返回“**eval("(" + val + ")")**”呢？这种情况下我没有办法正常取得设定好的data-value。

**Comment by ThorQin** [comment]
这个设定是因为我希望存储的数据全部为 json 或 js 格式的内容，这样访问 value() 方法得到可以得到任何想要的内容，如果是json可以得到对象，如果是js可以被执行后得到结果，当然这就要求在 html 标签中设置内容的时候也只能书写为 json或者js 格式，比如下面的代码：

```
<a id="chk1" class="tui-checkbox" data-value="'abc'">复选框1</a>
<script>
tui.ctrl.checkbox("chk1").on("click", function(){
    tui.msgbox(this.value());
});
</script>
```

在点击 chk1 的时候会显示字符串 abc，而如果写成 data-value="abc" 则不能取得正确内容，因为代码会理解为 abc 是个变量名，而 abc 如果之前没有定义过的话则得到的是 null(undefined 会被替换为 null)，当然如果 abc 被定义过则可以返回 abc 对应的值。总之 data-value 对应的是一个表达式，比如：

data-value="'abc'"
data-value="document.body.clientWidth + 100"
data-value="123"
data-value='{"name":"zhangsan", "age": 28}'
data-value="{a:1,b:2}"

这些都是支持的写法。

**Comment by xhy008** [comment]
明白了，谢谢解答。
