### ISSUE TITLE
关于tui.ctrl.input[type=file]控件的一些疑问

### ISSUE THREAD

**Issue by xhy008** [ThorQin/tui#4]
下面是我写的上传方法。其中有文件类型、文件大小错误的检查：
![2015-11-13_182316](https://cloud.githubusercontent.com/assets/716954/11143917/e0c3953a-8a33-11e5-9c58-ce2a8a7ac076.png)

问题一：当在IE9下，以下代码发生异常，而firefox下正常。推测其它IE版本可能也有同样的问题；
![2015-11-13_154750](https://cloud.githubusercontent.com/assets/716954/11143918/e0c631dc-8a33-11e5-8f5b-5b79ee04500d.png)

问题二：后台检查失败后，我想显示自己返回的异常消息，但目前file控件中只显示自己的消息。
![2015-11-13_182218](https://cloud.githubusercontent.com/assets/716954/11143919/e0c7c740-8a33-11e5-9158-13f7a23201e8.png)

以上两个问题，希望可以给些建议，谢谢。

**Comment by ThorQin** [comment]
由于受低版本ie上传文件方式的限制，要反回自定义消息不能使用 throw new HttpException 这种方法，只能自定义一个反回信息，然后在客户端拦截 **complete** 事件，比如：
服务器代码：

``` java
@WebEntry(method = HttpMethod.POST)
public WebContent upload(HttpServletRequest request, HttpServletResponse response) throws Exception {
    UploadManager uploadManager = app.createUploadManager();
    uploadManager.setFileSuffix("xlsx");
    try {
        List<UploadManager.FileInfo> infos = uploadManager.saveUploadFiles(request, 1024 * 10); // 10K
        if (infos.size() > 0) {
            return WebContent.text(Serializer.toJsonString(infos.get(0)));
        } else {
            return WebContent.text("{\"error\":\"文件类型不对\"}");
        }
    } catch (FileUploadBase.SizeLimitExceededException ex) {
        return WebContent.text("{\"error\":\"大小超过限制\"}");
    }
}
```

客户端代码：

``` html
<span id="upload" class="tui-input" data-type="file" data-upload-url="upload.do"></span>
<script>
tui.ctrl.input("upload").on("complete", function(data){
    if (data.response.error) {
        tui.errbox(data.response.error);
        return false; // 一定要 return false
    }
});
</script>
```

另外你说的IE9错误，我这里用 IE11 模拟的IE8,IE9 环境测试是可以的，我可以周1在公司在找个真正的IE8，9测试一下，按说之前别的项目应该是测试过IE8,9的，问题应该不大。

**Comment by xhy008** [comment]
好的，谢谢解答。如果后台不返回HttpException时，我想问题一也应该就不会出现了。

**Comment by xhy008** [comment]
IE9下，如果不返回HttpException，不会出问题一。

**Comment by ThorQin** [comment]
Ok.
